services:
  - type: web
    name: ekubo
    env: python
    runtime: python312

    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh

    envVars:
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: ekubo-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ekubo-redis
          property: connectionString
      - key: EMAIL_HOST_USER
        fromSecret: EMAIL_HOST_USER
      - key: EMAIL_HOST_PASSWORD
        fromSecret: EMAIL_HOST_PASSWORD

    disk:
      name: media
      mountPath: /app/media
      sizeGB: 1

  - type: redis
    name: ekubo-redis
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: ekubo-db
    plan: free
